---
- stat: path="{{ ansible_user_dir }}/.bin/hub"
  register: gh_binary

- unarchive: src="{{ hub_release }}" dest=/tmp remote_src=yes
  when: gh_binary.stat.exists == False

- copy: src=/tmp/hub-linux-amd64-{{ hub_version }}/bin/hub
        dest="{{ ansible_user_dir }}/.bin/hub"
        mode=0755 remote_src=yes
  when: gh_binary.stat.exists == False
