---
- copy:
    dest: /etc/yum.repos.d/dropbox.repo
    mode: 0644
    owner: root
    group: root
    content: |
      [Dropbox]
      name=Dropbox Repository
      enabled=1
      baseurl=http://linux.dropbox.com/fedora/$releasever/
      gpgkey=https://linux.dropbox.com/fedora/rpm-public-key.asc
      skip_if_unavailable=1
#- name: Get Dropbox rpm
#  dest=/tmp/dropbox.rpm url="https://www.dropbox.com/download?dl=packages/fedora/nautilus-dropbox-2015.10.28-1.fedora.x86_64.rpm"

#- dnf: name=/tmp/dropbox.rpm state=installed
