---
- name: Get EPEL rpm
  get_url: dest=/tmp/epel.rpm
           url="https://dl.fedoraproject.org/pub/epel/epel-release-latest-{{ ansible_distribution_version|int }}.noarch.rpm"
  when: ansible_os_family == "RedHat"

- yum: name=/tmp/epel.rpm state=installed
  when: ansible_os_family == "RedHat"
