---
- include: rhel.yml
  become: true
  when: ansible_distribution == 'RedHat'

- include: epel.yml
  become: true
  # centos & rhel
  when: '"epel" in use_repos and ansible_distribution != "Fedora" and ansible_os_family == "RedHat"'

- include: rpmfusion.yml
  become: true
  when: '"rpmfusion" in use_repos'

- include: chrome.yml
  become: true
  when: '"chrome" in use_repos'

- include: dropbox.yml
  become: true
  when: '"dropbox" in use_repos and ansible_distribution == "Fedora"'

- include: coprs.yml
  become: true
  when: 'use_coprs is defined and ansible_distribution == "Fedora"'

- include: rhpkg.yml
  become: true
  when: 'packaging_tools is defined and packaging_tools and ansible_distribution == "Fedora"'
