---
- name: Get rhpkg Fedora repository
  copy:
    dest: /etc/yum.repos.d/rhpkg.repo
    mode: 0644
    owner: root
    group: root
    # retrieved from https://mojo.redhat.com/docs/DOC-997854
    content: |
      [rcm-tools-fedora-rpms]
      name=RCM Tools for Fedora $releasever (RPMs)
      baseurl=http://download.devel.redhat.com/rel-eng/latest-RCMTOOLS-1-F-$releasever/compose/Everything/$basearch/os/
      enabled=1
      gpgcheck=0

- name: Install rhpkg/brew tools for Fedora and RHEL packaging
  dnf: name={{ item }} state=latest
  with_items:
    - rhpkg
    - brewkoji
    - fedpkg
    - koji
  tags:
    - packages

# get current groups first to avoid overwriting memberships
- command: groups
  become_user: ryansb
  changed_when: false
  register: current_groups
- user: name=ryansb group=ryansb groups='{{ current_groups.stdout.split(" ")[1:] | join(",") }},mock'
