---
- file: path=~/.bin
        state=directory

- include: packages.yml
  become: true
- include: vim.yml
- include: zsh.yml

### Other dotfiles
- file: path=~/.config/htop state=directory
- file: path=~/.config/htop state=directory
  become: true

- copy: dest=~/.{{ item }}
        src={{ item }}
  with_items:
  - gitconfig
  - hgrc
  - tmux.conf
  - tmux.theme.conf
  - screenrc
  - config/htop/htoprc

- copy: dest=~/.{{ item }}
        src={{ item }}
  become: true
  with_items:
  - screenrc
  - config/htop/htoprc

# this file needs to exist, but it just for local customizations
- file: path=~/.tmux.local state=touch
