---
- file: path=~/.bin
        state=directory

- include: packages.yml
  sudo: true
- include: vim.yml
- include: zsh.yml

### Other dotfiles
- copy: dest=~/.{{ item }}
        src={{ item }}
  with_items:
  - gitconfig
  - hgrc
  - tmux.conf
  - tmux.theme.conf
  - screenrc

# this file needs to exist, but it just for local customizations
- file: path=~/.tmux.local state=touch
