---
- yum: name={{ item }} state=latest
  with_items:
  - bind-utils
  - bzr
  - git
  - libguestfs-tools
  - mercurial
  - nc
  - ntpdate
  - openssh-clients
  - rsync
  - screen
  - strace
  - svn
  - tar
  - tmux
  - traceroute
  - vim-enhanced
  - xz
  tags:
    - packages
- yum: name={{ item }} state=latest
  with_items:
  - ack
  - ccze
  - htop
  - nload
  - ranger
  - ldns-utils
  - iotop
  - tig
  - mosh
  - pigz
  - pv
  ignore_errors: true
  tags:
    - packages
- yum: name={{ item }} state=absent
  with_items:
  # get rid or the "not found, want to install XYZ package?" prompt
  - PackageKit-command-not-found
