---
- file: path=/etc/unbound/{{ item }}/ state=directory mode=0755 owner=root group=unbound
  with_items:
  - local.d
  - conf.d

- shell: curl -s '{{ ad_dnsbl }}'
  register: ad_hosts
  no_log: true
  changed_when: false

- template: src=ad_servers.conf.j2
            dest=/etc/unbound/local.d/ad_servers.conf
            owner=root group=unbound mode=0644
  notify:
    - restart unbound

- copy:
    src: dlv.isc.org.key
    dest: /etc/unbound/keys.d/dlv.isc.org.key
    owner: root
    group: unbound
    mode: '0644'
  notify:
    - restart unbound

- copy: src=unbound.conf dest=/etc/unbound/unbound.conf
        owner=root group=unbound mode=0644
  notify:
    - restart unbound

- copy: src=conf.d/local.conf dest=/etc/unbound/conf.d/local.conf
        owner=root group=unbound mode=0644

- copy: src=local-insecure.conf dest=/etc/unbound/local.d/local.conf
        owner=root group=unbound mode=0644

- copy: src=conf.d/redhat.com.conf dest=/etc/unbound/conf.d/redhat.com.conf
        owner=root group=unbound mode=0644
  when: override_rht_zone
  notify:
    - restart unbound

- name: unbound | skip mdns for host lookup
  lineinfile:
    dest: /etc/nsswitch.conf
    regexp: '^hosts:'
    line: "hosts:      files dns myhostname mymachines mdns4_minimal"
    backup: yes
