---
- dnf: name=unbound state=latest
  become: true
  tags:
    - packages

- dnf: name="{{ item }}" state=latest
  become: true
  with_items:
  - dnssec-trigger
  - dnssec-trigger-panel
  tags:
    - packages
  when: '"gui" in group_names'

- shell: creates=/etc/unbound/unbound_control.key unbound-control-setup
  become: true

- include: conf.yml
  become: true
