---
- yum: name=unbound state=latest
  sudo: true
  tags:
    - packages

- yum: name="{{ item }}" state=latest
  sudo: true
  with_items:
  - dnssec-trigger
  - dnssec-trigger-panel
  tags:
    - packages
  when: '"gui" in group_names'

- file: path=/etc/unbound/{{ item }}/ state=directory mode=0755 owner=root group=unbound
  with_items:
  - local.d
  - conf.d
  sudo: True

- shell: curl -s '{{ ad_dnsbl }}'
  register: ad_hosts

- template: src=ad_servers.conf.j2
            dest=/etc/unbound/local.d/ad_servers.conf
            owner=root group=unbound mode=0644
  sudo: True
  notify:
    - restart unbound

- copy: src=unbound.conf dest=/etc/unbound/unbound.conf
        owner=root group=unbound mode=0644
  sudo: True
  notify:
    - restart unbound

- copy: src=conf.d/redhat.com.conf dest=/etc/unbound/conf.d/redhat.com.conf
        owner=root group=unbound mode=0644
  sudo: True
  when: "{{ override_rht_zone }}"
  notify:
    - restart unbound
