---
# Credit to https://github.com/ralphbean/snackpack/blob/cb9952c062013d0088e359fac36bf4de89f1d8ba/playbooks/site.yml#L46-L69
- name: Install package required for accelerate mode
  dnf: name={{ item }} state=installed
  with_items:
    - python-keyczar
    - openssl-devel
- name: Open the ansible accelerate port
  firewalld: >
      port=10319/tcp
      state=enabled
      zone=public
      permanent=true
  notify:
    - restart firewalld
