- dnf: name=fail2ban-systemd state=present
  notify: restart fail2ban
  tags:
  - packages

- name: Enable sshd filtering
  copy: src=00-sshd.conf
        dest=/etc/fail2ban/jail.d/00-sshd.conf
  notify: restart fail2ban

- copy: src=fail2ban.conf
        dest=/etc/fail2ban/fail2ban.conf
  notify: restart fail2ban

- service:
    name: fail2ban
    enabled: yes
    state: started
  notify: restart fail2ban
