- dnf: name=firewalld state=present
  tags:
  - packages

- dnf: name=python-firewall state=present
  tags:
  - packages

# On Pidora the firewalld unit is masked
- file:
      path: /etc/systemd/system/firewalld.service
      follow: yes
  register: firewalld_unit
  failed_when: False

- command: /usr/bin/systemctl unmask firewalld
  when: firewalld_unit.state != 'absent' and firewalld_unit.src == '/dev/null'

- service: name=firewalld
           enabled=true
           state=started

- command: firewall-cmd --get-zones
  register: firewall_zones

- command: firewall-cmd --get-default-zone
  register: firewall_default_zone
  changed_when: false

- shell: firewall-cmd --permanent --new-zone={{ firewalld_zone }} && firewall-cmd --reload
  when: firewalld_zone not in firewall_zones.stdout

- firewalld:
    zone: "{{ firewalld_zone }}"
    permanent: yes
    immediate: yes
    state: enabled
    service: "{{ item }}"
  with_items: "{{ enabled_services }}"

- firewalld:
    zone: "{{ firewalld_zone }}"
    permanent: yes
    immediate: yes
    state: enabled
    port: 22/tcp

- firewalld:
    zone: "{{ firewalld_zone }}"
    permanent: yes
    immediate: yes
    state: enabled
    port: "{{ item }}"
  with_items: "{{ enabled_ports }}"

- command: firewall-cmd --set-default-zone={{ firewalld_zone }}
  when: firewalld_zone not in firewall_default_zone.stdout
