---
- include: sshd.yml
  sudo: true
  when: secure_ssh
- include: firewalld.yml
  sudo: true
  when: secure_firewalld
- include: fail2ban.yml
  sudo: true
  when: secure_fail2ban

# ipv6? Check it if you have it.
- include: ipv6.yml
  sudo: true
  when: ansible_default_ipv6 != {} and secure_ipv6

- name: Add SSH keys from github
  authorized_key: user=ryansb key=https://github.com/ryansb.keys
  when: ansible_user_id == "ryansb"

- name: Add root SSH keys
  authorized_key: user=root key=https://github.com/ryansb.keys
  sudo: true
