---
- name: ssh | skip mdns for host lookup because it breaks all the **** time
  become: true
  lineinfile:
    dest: /etc/nsswitch.conf
    regexp: '^hosts:'
    line: "hosts:      files dns myhostname mymachines mdns4_minimal"
    backup: yes

- name: create ~/.ssh
  file:
    path: /home/ryansb/.ssh
    state: directory
    mode: '0700'

- name: SSH config
  template:
    dest: /home/ryansb/.ssh/config
    mode: '0600'
    src: 'ssh-config.j2'
