---
# tasks file for rhosp
- include: packages.yml
  become: true

- user: name=stack createhome=yes
        home=/home/stack
  become: true

- copy: content="stack ALL=(root) NOPASSWD:ALL"
        dest=/etc/sudoers.d/stack mode=0440
  become: true

- get_url:
    dest: "/home/stack/{{ rhel_guest_image_name }}"
    group: stack
    mode: '0644'
    owner: stack
    url: "{{ rhel_guest }}"
  become: true

- name: Add SSH keys for stack user in undercloud
  become: true
  become_user: stack
  authorized_key: user=stack key=https://github.com/ryansb.keys

- name: Add root SSH keys
  authorized_key: user=root key=https://github.com/ryansb.keys
  become: true

- copy:
    dest: /home/stack/instack-vars
    content: |
      export NODE_DIST=rhel7
      export IMAGE={{ rhel_guest }}
      export DIB_LOCAL_IMAGE=`basename $IMAGE`
      export DIB_YUM_REPO_CONF="/etc/yum.repos.d/rhos-release-7.repo /etc/yum.repos.d/rhos-release-rhel-7.1.repo /etc/yum.repos.d/rhos-release-7-director.repo"
      export NODE_COUNT=5
      export UNDERCLOUD_NODE_CPU=4
      export UNDERCLOUD_NODE_MEM=16384
  become: true

- include: undercloud.yml
  become: true
  become_user: stack
  when: undercloud

  # add a route directly to undercloud public network
- shell: ip route add 192.0.2.0/24 dev virbr0
  become: true
  when: not undercloud
  ignore_errors: true
