---
# tasks file for rhosp
- include: packages.yml
  sudo: true

- user: name=stack createhome=yes
        home=/home/stack
  sudo: true

- copy: content="stack ALL=(root) NOPASSWD:ALL"
        dest=/etc/sudoers.d/stack mode=0440
  sudo: true

- get_url:
    url: "http://download.devel.redhat.com/brewroot/packages/rhel-guest-image/7.1/20150224.0/images/rhel-guest-image-7.1-20150224.0.x86_64.qcow2"
    dest: /home/stack/rhel-guest-image-7.1-20150224.0.x86_64.qcow2
  sudo: true

- copy:
    dest: /home/stack/instack-vars
    content: |
      export NODE_DIST=rhel7
      export IMAGE=http://download.devel.redhat.com/brewroot/packages/rhel-guest-image/7.1/20150224.0/images/rhel-guest-image-7.1-20150224.0.x86_64.qcow2
      export DIB_LOCAL_IMAGE=`basename $IMAGE`
      export DIB_YUM_REPO_CONF="/etc/yum.repos.d/rhos-release-7-director-rhel-7.1.repo /etc/yum.repos.d/rhos-release-7-rhel-7.1.repo"
      export NODE_COUNT=5
      export UNDERCLOUD_NODE_CPU=4
      export UNDERCLOUD_NODE_MEM=16384
  sudo: true
