---
# tasks file for virt
- yum: name="{{ item }}" state=latest
  sudo: true
  with_items:
  - libvirt
  - libvirt-daemon-kvm
  - libvirt-python
- include: virt-networks.yml
  sudo: true
- include: virt-disks.yml
  when: post_create
  sudo: true
