---
- yum: name=libreswan state=latest
  sudo: true
  tags:
  - packages

- copy: dest=item[0] src=item[1] owner=root group=root
  sudo: true
  with_items_nested:
  - [/etc/ipsec.d/redhat.secrets, /etc/ipsec.conf]
  - [vpn_secret, ipsec.conf]
