---
- yum: name=libreswan state=latest
  tags:
  - packages

- copy: dest=/etc/ipsec.d/redhat.secrets content="{{ vpn_secret }}"
        owner=root group=root
  notify: restart ipsec

- template: dest=/etc/ipsec.conf src=ipsec.conf
            owner=root group=root
  notify: restart ipsec

- service: name=ipsec enabled=true

- lineinfile:
      dest: /root/.bashrc
      regexp: "^alias vpn"
      line: 'alias vpn="systemctl restart ipsec && sleep 5 && ipsec auto --up redhat"'
      backup: yes

- pause: seconds=180 prompt="waiting for user to run `vpn` as root"
