---
- yum: name=libreswan state=latest
  sudo: true
  tags:
  - packages

- copy: dest=/etc/ipsec.d/redhat.secrets content="{{ vpn_secret }}"
        owner=root group=root
  sudo: true
  notify: restart ipsec

- template: dest=/etc/ipsec.conf src=ipsec.conf
            owner=root group=root
  sudo: true
  notify: restart ipsec

- service: name=ipsec enabled=true

- lineinfile:
      dest: /root/.bashrc
      regexp: "^alias vpn"
      line: "alias vpn="systemctl restart ipsec && sleep 5 && ipsec auto --up redhat"
      backup: yes
