---
# To bring this up by CLI, you need to supply a password
# sudo nmcli con up rhvpn --ask
- name: copy openvpn config template
  template:
    src: networkmanager-ovpn.conf
    dest: /etc/NetworkManager/system-connections/rhvpn
    mode: '0600'
    owner: root
    group: root
  notify: restart NetworkManager
