#
# Defines environment variables.
#

# Ensure that a non-login, non-interactive shell has a defined environment.
if [[ "$SHLVL" -eq 1 && ! -o LOGIN && -s "${ZDOTDIR:-$HOME}/.zprofile" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprofile"
fi
#
# Browser
#

if [[ "$OSTYPE" == darwin* ]]; then
  export BROWSER='open'
fi

#
# Editors
#

export EDITOR='vim'
export VISUAL='vim'
export PAGER='less'

setopt interactivecomments

#
# Language
#

if [[ -z "$LANG" ]]; then
  export LANG='en_US.UTF-8'
fi

#
# Paths
#

typeset -gU cdpath fpath mailpath path manpath

# Set the the list of directories that cd searches.
# cdpath=(
#   $cdpath
# )

if [[ -d $HOME/.golang ]]; then
  export GOROOT="$HOME/.golang"
else
  export GOROOT="/usr/lib/golang"
fi

export GOPATH="$HOME/remotes"
export PYENV_ROOT="$HOME/.pyenv"
export RBENV_ROOT="$HOME/.rbenv"

# Set the list of directories that Zsh searches for programs.
path=(
  $HOME/.bin
  $HOME/.local/bin
  $HOME/.cabal/bin
  $GOPATH/bin
  $GOROOT/bin
  /usr/local/{bin,sbin}
  $path
)

#
# Less
#

# Set the default Less options.
# Mouse-wheel scrolling has been disabled by -X (disable screen clearing).
# Remove -X and -F (exit if the content fits on one screen) to enable it.
export LESS='-F -g -i -M -R -S -w -X -z-4'

# Set the Less input preprocessor.
if (( $+commands[lesspipe.sh] )); then
  export LESSOPEN='| /usr/bin/env lesspipe.sh %s 2>&-'
fi

#
# Temporary Files
#

if [[ ! -d "$TMPDIR" ]]; then
  export TMPDIR="/tmp/$USER"
  mkdir -p -m 700 "$TMPDIR"
fi

TMPPREFIX="${TMPDIR%/}/zsh"
if [[ ! -d "$TMPPREFIX" ]]; then
  mkdir -p "$TMPPREFIX"
fi

eval "$(which pyenv 2>/dev/null && pyenv virtualenv-init -)" 2>/dev/null

# added for https://github.com/tj/n by http://git.io/n-install-repo
export N_PREFIX="$HOME/.local/n"; [[ :$PATH: == *":$N_PREFIX/bin:"* ]] || PATH+=":$N_PREFIX/bin"

# The next line updates PATH for the Google Cloud SDK.
source '/home/ryansb/.local/google-cloud-sdk/path.zsh.inc' 2>/dev/null

# The next line enables shell command completion for gcloud.
source '/home/ryansb/.local/google-cloud-sdk/completion.zsh.inc' 2>/dev/null
