---
pyenv_version: 'v20160726'
pyenv_venv_version: 'v20160716'
python_installs:
 - 2.7.10
 - 3.3.6
 - 3.4.3
 - 3.5.2

rbenv_version: 'master'
rbenv_build_version: 'v20150818'
ruby_installs:
  - 2.2.2
