---
rhel_guest: "http://download.devel.redhat.com/brewroot/packages/rhel-guest-image/7.1/20150224.0/images/rhel-guest-image-7.1-20150224.0.x86_64.qcow2"
rhel_guest_image_name: "rhel-guest-image-7.1-20150224.0.x86_64.qcow2"
undercloud: false

undercloud_images:
  - name: deploy-ramdisk-ironic.tar
    contains: deploy-ramdisk-ironic.kernel
    url: "http://rhos-release.virt.bos.redhat.com/mburns/latest-images/deploy-ramdisk-ironic.tar"
  - name: discovery-ramdisk.tar
    contains: discovery-ramdisk.kernel
    url: "http://rhos-release.virt.bos.redhat.com/mburns/latest-images/discovery-ramdisk.tar"
  - name: overcloud-full.tar
    contains: overcloud-full.qcow2
    url: "http://rhos-release.virt.bos.redhat.com/mburns/latest-images/overcloud-full.tar"
