---
- name: Configure GUI workstation
  hosts: gui
  vars_files:
    - ../vars/global.yml
    - ../vars/secrets.yml
  roles:
    - ssh
    - security
    #- unbound
    - vpn
    - krb5
    - repos
    - shell
    - languages
    - productivity
    - irc
    - backup
