---
- name: Configure GUI workstation
  hosts: gui
  vars_files:
    - ../vars/global.yml
  roles:
    - security
    - unbound
    - repos
    - shell
    - languages
    - productivity
    - irc
    - backup
