---
- dnf: name={{ item }} state=latest
  name: install R, Go, and Haskell
  become: true
  with_items:
  - haskell-platform
  - R
  - autoconf
  - make
  - golang
  tags:
    - packages
  when: ansible_distribution == 'Fedora'

- include: python.yml
- include: ruby.yml

- block:
  - name: grab n install script
    get_url:
      url: https://git.io/n-install
      dest: ~/.bin/n-install.sh
      mode: '0754'
  - name: Install node version manager and make sure stable & LTS are installed
    shell: >
      ~/.bin/n-install.sh -y -n stable lts
    environment:
      N_PREFIX: '{{ ansible_user_dir }}/.local/n'
    args:
      creates: '{{ ansible_user_dir }}/.local/n/bin/n'

- name: make R module dir
  file: path=~/.rlang/lib/ state=directory
- copy: src=Rprofile dest=~/.Rprofile
- copy: src=Renviron dest=~/.Renviron
