---
- dnf: name={{ item }} state=latest
  name: install R, Go, and Haskell
  become: true
  with_items:
  - haskell-platform
  - R
  - autoconf
  - make
  - golang
  tags:
    - packages
  when: ansible_distribution == 'Fedora'

- include: python.yml
- include: ruby.yml

- name: Install node version manager and make sure stable & LTS are installed
  shell: >
    curl -vsL https://git.io/n-install | N_PREFIX=~/.local/n bash -s -- -n stable lts
  args:
    creates: /home/ryansb/.local/n/bin/n

- name: make R module dir
  file: path=~/.rlang/lib/ state=directory
- copy: src=Rprofile dest=~/.Rprofile
- copy: src=Renviron dest=~/.Renviron
