---
- dnf: name={{ item }} state=latest
  become: true
  with_items:
  - gcc
  - patch
  - openssl-devel
  - libxml2-devel
  - libxslt-devel
  - postgresql-devel
  - python-setuptools
  - python-devel
  - readline-devel
  - sqlite-devel
  - readline-devel
  - zlib-devel
  - bzip2-devel
  tags:
  - packages
  when: ansible_distribution != 'MacOSX'

- homebrew:
  with_items:
  - gcc
  - patch
  tags:
  - packages
  when: ansible_distribution == 'MacOSX'

- name: optional stuff to make some libs faster
  dnf: name={{ item }} state=latest
  become: true
  ignore_errors: true
  with_items:
  - blas-devel
  - libyaml-devel
  tags:
  - packages

# yeah, sudo easy_install is a bit gross, but it's ok in this case
- command: creates=/bin/pip easy_install pip
  become: true
  tags:
    - packages


- file: state=directory name=~/.local

- shell: creates=~/.local/bin/tox
         pipsi install tox

- shell: creates=~/.local/bin/harvey
         pipsi install harvey

- git: repo=https://github.com/pyenv/pyenv.git
       dest=~/.pyenv
       version={{ pyenv_version }}

- git: repo=https://github.com/pyenv/pyenv-virtualenv.git
       dest=~/.pyenv/plugins/pyenv-virtualenv
       version={{ pyenv_venv_version }}

- name: install needed python versions
  shell: creates=~/.pyenv/versions/{{ item }}
         ~/.pyenv/bin/pyenv install {{ item }}
  with_items: "{{ python_installs }}"

- name: copy venv-node script to ~/.bin
  copy: src=venv_node dest=~/.bin/venv_node mode='0755'
