---
- name: restart fail2ban
  sudo: true
  service: name=fail2ban state=restarted

- name: restart sshd
  sudo: true
  service: name=sshd state=restarted

- name: restart firewalld
  sudo: true
  service: name=firewalld state=restarted
